apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
data:
  POSTGRES_PASSWORD: <your-base64-encoded-password> # Replace with your base64 encoded password
type: Opaque # The default secret type if not specified
