apiVersion: v1
kind: Service
metadata:
  name: dev-record-server
spec:
  type: ClusterIP
  selector:
    app: dev-record-server
  ports:
    - name: http
      port: 8005
      targetPort: 8005
    - name: grpc
      port: 50055
      targetPort: 50055