apiVersion: apps/v1
kind: Deployment
metadata:
  name: rabbitmq-deployment
  labels:
    app: rabbitmq
spec:
  replicas: 1                   # Single instance for development
  selector:
    matchLabels:
      app: rabbitmq
  template:
    metadata:
      labels:
        app: rabbitmq
    spec:
      containers:
        - name: rabbitmq
          image: rabbitmq:3-management-alpine # Includes management UI
          ports:
            - containerPort: 5672  # RabbitMQ broker port
            - containerPort: 15672 # Management UI port
          envFrom:
            - secretRef:
                name: rabbitmq-secret
            - configMapRef:
                name: rabbitmq-config
          volumeMounts:
            - name: rabbitmq-storage
              mountPath: /var/lib/rabbitmq # Persistent data location
      volumes:
        - name: rabbitmq-storage
          persistentVolumeClaim:
            claimName: rabbitmq-pvc # PVC created separately
