# nexus-service.yaml
apiVersion: v1
kind: Service
metadata:
  name: nexus
spec:
  selector:
    app: nexus
  ports:
    - name: http
      port: 8081
      targetPort: 8081
      nodePort: 30081
    - name: docker-registry
      protocol: TCP
      port: 5000
      targetPort: 5000
      nodePort: 30500
  type: NodePort
