apiVersion: apps/v1
kind: Deployment
metadata:
  name: nexus
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nexus
  template:
    metadata:
      labels:
        app: nexus
    spec:
      containers:
        - name: nexus
          image: sonatype/nexus3:3.82.0
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8081
          env:
            - name: NEXUS_HOSTNAME
              value: "nexus"
            # Optional JVM tuning for stability on limited memory
            - name: INSTALL4J_ADD_VM_PARAMS
              value: "-Xms512m -Xmx1500m -XX:MaxDirectMemorySize=2g"
          volumeMounts:
            - name: nexus-storage
              mountPath: /nexus-data  # Nexus requires this exact mount point
          resources:
            requests:
              cpu: "250m"
              memory: "1Gi"
            limits:
              cpu: "500m"
              memory: "2Gi"
      volumes:
        - name: nexus-storage
          persistentVolumeClaim:
            claimName: nexus-pvc