apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nexus-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi   # recommended for anything but very small test setups
  volumeMode: Filesystem
  # storageClassName: <your-storage-class>   # uncomment / set if you have a preferred storage class
