apiVersion: v1
kind: ConfigMap
metadata:
  name: shared-config
data:
  # ---------- PostgreSQL ----------
  POSTGRES_HOST: postgres-stf
  POSTGRES_PORT: "5432"

  # ---------- RabbitMQ ----------
  RMQ_HOST: rabbitmq-stf
  RMQ_PORT: "5672"
  RMQ_ADDRESSES: rabbitmq-stf:15672

  # ---------- Redis ----------
  SPRING_REDIS_HOST: redis-service
  SPRING_REDIS_PORT: "6379"
  SPRING_REDIS_PASSWORD: redis
  REDIS_HOST: redis-service
  REDIS_PASSWORD: redis

  # ---------- Elasticsearch ----------
  DEV_ELASTIC_PROPERTY_HOST: elasticsearch-stf
  DEV_ELASTIC_PROPERTY_PORT: "9200"
  DEV_ELASTIC_PROPERTY_SCHEME: http

  grpc.client.__dev-auth-server__.address: static://dev-auth-server:50050
  grpc.client.__dev-auth-server__.negotiationType: PLAINTEXT
  grpc.client.__dev-record_server__.address: static://dev-record-server:50055
  grpc.client.__dev-record_server__.negotiationType: PLAINTEXT
