apiVersion: v1
kind: Service
metadata:
  name: nexus-registry
spec:
  selector:
    app: nexus
  type: NodePort
  ports:
    - name: registry
      port: 5000
      targetPort: 5000
      nodePort: 32000