apiVersion: v1
kind: Service
metadata:
  name: nexus-service
  labels:
    app: nexus               # Identifies Nexus Repository components
spec:
  type: ClusterIP            # Keep internal; access UI/registry using port-forward
  selector:
    app: nexus               # Targets Nexus pod
  ports:
    - name: nexus-ui
      port: 8081             # Web UI port
      targetPort: 8081
    - name: docker-registry
      port: 5000             # Internal Docker registry port
      targetPort: 5000

#apiVersion: v1
#kind: Service
#metadata:
#  name: nexus-registry
#  labels:
#    app: nexus
#spec:
#  type: NodePort
#  selector:
#    app: nexus
#  ports:
#    - name: docker-registry
#      port: 5000
#      targetPort: 5000
#      nodePort: 30500
