apiVersion: v1
kind: Secret
metadata:
  name: nexus-secret
  namespace: default   # change if needed
type: Opaque
data:
  username: YWRtaW4=      # base64 of 'admin'
  password: YWRtaW4xMjM=  # base64 of 'admin123'
