# =============================================================
# Kubernetes Setup for Sonatype Nexus Repository Manager
# =============================================================

# -------------------------------------------------------------
# Persistent Volume Claim — ensures data (images, artifacts)
#     are stored on disk, not lost when pods restart.
# -------------------------------------------------------------
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nexus-pvc
  labels:
    app: nexus
spec:
  accessModes:
    - ReadWriteOnce           # One node can mount the volume at a time — typical for stateful apps
  resources:
    requests:
      storage: 10Gi           # Allocate 10GB for storing Docker images and Maven artifacts
  storageClassName: standard  # Default Minikube storage class

