apiVersion: v1
kind: ConfigMap
metadata:
  name: dev-auth-server-config
  labels:
    app: dev-auth-server
data:
  # ------------ PostgreSQL --------------
  SPRING_DATASOURCE_URL: jdbc:postgresql://postgres-stf:5432/dev_auth_server

  # ------------ RabbitMQ ----------------
  auth_rabbit_host: rabbitmq-stf
  auth_rabbit_port: "5672"
  auth_rabbit_management-base-url: http://rabbitmq-stf:15672/api
  auth_oauth_redirect: https://awards-colored-believes-alike.trycloudflare.com/auth/callback


  # ------------ Redis -------------------
  SPRING_DATA_REDIS_HOST: redis-service
  SPRING_DATA_REDIS_PORT: "6379"
  SPRING_DATA_REDIS_PASSWORD: redis
  #  SPRING_DATA_REDIS_DATABASE: "0"

  SPRING_DATA_REDIS_TIMEOUT: 2s

  SPRING_DATA_REDIS_POOL_MAX_ACTIVE: "50"
  SPRING_DATA_REDIS_POOL_MAX_IDLE: "10"
  SPRING_DATA_REDIS_POOL_MIN_IDLE: "2"

  # ------------ Elasticsearch -----------
  DEV_ELASTIC_PROPERTY_HOST: elasticsearch-stf
  DEV_ELASTIC_PROPERTY_PORT: "9200"
  DEV_ELASTIC_PROPERTY_SCHEME: http

  grpc.client.__dev-sandbox__.address: static://dev-sandbox:50051
  grpc.client.__dev-sandbox__.negotiationType: PLAINTEXT

  grpc.client.__dev-integration__.address: static://dev-integration:50052
  grpc.client.__dev-integration__.negotiationType: PLAINTEXT

  grpc.client.__dev-record_server__.address: static://dev-record-server:50055
  grpc.client.__dev-record_server__.negotiationType: PLAINTEXT

  grpc.client.__dev-email__.address: static://dev-email-server:50057
  grpc.client.__dev-email__.negotiationType: PLAINTEXT


