apiVersion: v1
kind: Service
metadata:
  name: dev-auth-service
spec:
  type: NodePort                  # Exposes service to your local machine via Node IP
  selector:
    app: dev-auth
  ports:
    - port: 8000                  # Service port inside cluster
      targetPort: 8000            # Port Spring Boot exposes
      nodePort: 30081             # Exposed on minikube IP