apiVersion: v1
kind: Service
metadata:
  name: dev-auth-service
  labels:
    app: dev-auth             # Helps with filtering and organizing
spec:
  type: NodePort              # Expose app outside cluster via NodePort on minikube
  selector:
    app: dev-auth             # Matches pods with this label
  ports:
    - name: http              # Optional, for clarity in observability
      port: 8000              # Port the service exposes inside the cluster
      targetPort: 8000        # Port exposed by the container
      nodePort: 30081         # Must be in range 30000-32767
