apiVersion: apps/v1
kind: Deployment
metadata:
  name: dev-auth
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dev-auth
  template:
    metadata:
      labels:
        app: dev-auth
    spec:
      containers:
        - name: dev-auth
          image: dev-auth:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8000
          env:
            - name: SPRING_DATASOURCE_URL
              value: jdbc:postgresql://postgres-service:5432/dev_auth
            - name: SPRING_DATASOURCE_USERNAME
              value: postgres
            - name: SPRING_DATASOURCE_PASSWORD
              value: root
