apiVersion: v1
kind: ConfigMap
metadata:
  name: elasticsearch-config
  labels:
    app: elasticsearch
data:
  # Basic Elasticsearch settings
  discovery.type: single-node      # Required for single-node setup in dev
  ES_JAVA_OPTS: "-Xms512m -Xmx512m" # JVM heap size
