apiVersion: v1
kind: Service
metadata:
  name: elasticsearch-service
  labels:
    app: elasticsearch       # Identifies Elasticsearch resources
spec:
  type: ClusterIP            # Internal API access
  selector:
    app: elasticsearch       # Targets Elasticsearch pod
  ports:
    - name: rest
      port: 9200             # REST API used by your Spring Boot services
      targetPort: 9200
    - name: transport
      port: 9300             # Node-to-node clustering (not exposed outside)
      targetPort: 9300
