apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: elasticsearch-pvc
  labels:
    app: elasticsearch
spec:
  accessModes:
    - ReadWriteOnce                 # Only one pod can write at a time (sufficient for single-node dev)
  resources:
    requests:
      storage: 2Gi                  # Allocate 2GB storage for indices
  storageClassName: standard
