apiVersion: v1
kind: Service                      # Service provides a stable network identity and IP for pods

metadata:
  name: postgres-service            # Name of the service
  labels:
    app: postgres

spec:
  type: ClusterIP                   # 'ClusterIP' makes the service accessible *only* inside the cluster
                                   # Other options:
                                   # - NodePort: exposes on host machine (for browser access)
                                   # - LoadBalancer: used in cloud clusters (AWS/GCP)
  selector:
    app: postgres                   # Routes traffic to pods with this label (matches Deployment)

  ports:
    - port: 5432                    # Port clients use to connect to this service
      targetPort: 5432              # Port on the pod's container where the app is listening

# - This creates an internal DNS entry: postgres-service.dev-station.svc.cluster.local
# - Your Spring Boot microservices can use hostname "postgres-service" and port 5432 to connect.
