apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgres-volume
  labels:
    app:  postgres
    type: local
spec: 
  storageClassName: manual
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: /data/postgresql


