apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: formix-ingress
#  annotations:
#    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  rules:
    - host: formix.local.org
      http:
        paths:

          # Angular frontend
          - path: /
            pathType: Prefix
            backend:
              service:
                name: formix-ui-service
                port:
                  number: 80

          # API → Gateway
          - path: /dev
            pathType: Prefix
            backend:
              service:
                name: dev-ms-gateway
                port:
                  number: 8080

          - path: /dev-auth-server
            pathType: Prefix
            backend:
              service:
                name: dev-auth-server
                port:
                  number: 8000

          - path: /dev-integration
            pathType: Prefix
            backend:
              service:
                name: dev-integration
                port:
                  number: 8001

          - path: /dev-sandbox
            pathType: Prefix
            backend:
              service:
                name: dev-sandbox
                port:
                  number: 8002

          - path: /dev-email-server
            pathType: Prefix
            backend:
              service:
                name: dev-email-server
                port:
                  number: 8003

          - path: /dev-form-registry
            pathType: Prefix
            backend:
              service:
                name: dev-form-registry
                port:
                  number: 8004

          - path: /dev-record-server
            pathType: Prefix
            backend:
              service:
                name: dev-record-server
                port:
                  number: 8005
