apiVersion: v1
kind: Service
metadata:
  name: dev-integration
spec:
  type: ClusterIP
  selector:
    app: dev-integration
  ports:
    - name: http
      port: 8000
      targetPort: 8000

    - name: grpc
      port: 50052
      targetPort: 50052